apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: <Image>
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
